//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RequestCancelAMRAction", ReplyAction="http://tempuri.org/IService1/RequestCancelAMRActionResponse")]
        RobotServices.RequestCancelAMRActionResult RequestCancelAMRAction(string AMRId, string ActionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RequestCancelAMRAction", ReplyAction="http://tempuri.org/IService1/RequestCancelAMRActionResponse")]
        System.Threading.Tasks.Task<RobotServices.RequestCancelAMRActionResult> RequestCancelAMRActionAsync(string AMRId, string ActionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RequestCancelAMRActionGroup", ReplyAction="http://tempuri.org/IService1/RequestCancelAMRActionGroupResponse")]
        RobotServices.RequestCancelAMRActionGroupResult RequestCancelAMRActionGroup(string AMRId, string ActionGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RequestCancelAMRActionGroup", ReplyAction="http://tempuri.org/IService1/RequestCancelAMRActionGroupResponse")]
        System.Threading.Tasks.Task<RobotServices.RequestCancelAMRActionGroupResult> RequestCancelAMRActionGroupAsync(string AMRId, string ActionGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RequestAMRAction", ReplyAction="http://tempuri.org/IService1/RequestAMRActionResponse")]
        RobotServices.RequestAMRActionResult RequestAMRAction(RobotServices.RequestAMRActionArg[] arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RequestAMRAction", ReplyAction="http://tempuri.org/IService1/RequestAMRActionResponse")]
        System.Threading.Tasks.Task<RobotServices.RequestAMRActionResult> RequestAMRActionAsync(RobotServices.RequestAMRActionArg[] arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RequestTempChangeAMRArea", ReplyAction="http://tempuri.org/IService1/RequestTempChangeAMRAreaResponse")]
        RobotServices.RequestTempChangeAMRAreaResult RequestTempChangeAMRArea();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RequestTempChangeAMRArea", ReplyAction="http://tempuri.org/IService1/RequestTempChangeAMRAreaResponse")]
        System.Threading.Tasks.Task<RobotServices.RequestTempChangeAMRAreaResult> RequestTempChangeAMRAreaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNowAMRActionStatus", ReplyAction="http://tempuri.org/IService1/GetNowAMRActionStatusResponse")]
        RobotServices.GetNowAMRActionStatusResult GetNowAMRActionStatus(string AMRId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNowAMRActionStatus", ReplyAction="http://tempuri.org/IService1/GetNowAMRActionStatusResponse")]
        System.Threading.Tasks.Task<RobotServices.GetNowAMRActionStatusResult> GetNowAMRActionStatusAsync(string AMRId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNowAMRStatus", ReplyAction="http://tempuri.org/IService1/GetNowAMRStatusResponse")]
        RobotServices.GetNowAMRStatusResult GetNowAMRStatus(string AMRId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNowAMRStatus", ReplyAction="http://tempuri.org/IService1/GetNowAMRStatusResponse")]
        System.Threading.Tasks.Task<RobotServices.GetNowAMRStatusResult> GetNowAMRStatusAsync(string AMRId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNowAMRErrors", ReplyAction="http://tempuri.org/IService1/GetNowAMRErrorsResponse")]
        RobotServices.GetNowAMRErrorsResult GetNowAMRErrors(string AMRId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNowAMRErrors", ReplyAction="http://tempuri.org/IService1/GetNowAMRErrorsResponse")]
        System.Threading.Tasks.Task<RobotServices.GetNowAMRErrorsResult> GetNowAMRErrorsAsync(string AMRId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.IService1>, WindowsFormsApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public RobotServices.RequestCancelAMRActionResult RequestCancelAMRAction(string AMRId, string ActionId) {
            return base.Channel.RequestCancelAMRAction(AMRId, ActionId);
        }
        
        public System.Threading.Tasks.Task<RobotServices.RequestCancelAMRActionResult> RequestCancelAMRActionAsync(string AMRId, string ActionId) {
            return base.Channel.RequestCancelAMRActionAsync(AMRId, ActionId);
        }
        
        public RobotServices.RequestCancelAMRActionGroupResult RequestCancelAMRActionGroup(string AMRId, string ActionGroupId) {
            return base.Channel.RequestCancelAMRActionGroup(AMRId, ActionGroupId);
        }
        
        public System.Threading.Tasks.Task<RobotServices.RequestCancelAMRActionGroupResult> RequestCancelAMRActionGroupAsync(string AMRId, string ActionGroupId) {
            return base.Channel.RequestCancelAMRActionGroupAsync(AMRId, ActionGroupId);
        }
        
        public RobotServices.RequestAMRActionResult RequestAMRAction(RobotServices.RequestAMRActionArg[] arg) {
            return base.Channel.RequestAMRAction(arg);
        }
        
        public System.Threading.Tasks.Task<RobotServices.RequestAMRActionResult> RequestAMRActionAsync(RobotServices.RequestAMRActionArg[] arg) {
            return base.Channel.RequestAMRActionAsync(arg);
        }
        
        public RobotServices.RequestTempChangeAMRAreaResult RequestTempChangeAMRArea() {
            return base.Channel.RequestTempChangeAMRArea();
        }
        
        public System.Threading.Tasks.Task<RobotServices.RequestTempChangeAMRAreaResult> RequestTempChangeAMRAreaAsync() {
            return base.Channel.RequestTempChangeAMRAreaAsync();
        }
        
        public RobotServices.GetNowAMRActionStatusResult GetNowAMRActionStatus(string AMRId) {
            return base.Channel.GetNowAMRActionStatus(AMRId);
        }
        
        public System.Threading.Tasks.Task<RobotServices.GetNowAMRActionStatusResult> GetNowAMRActionStatusAsync(string AMRId) {
            return base.Channel.GetNowAMRActionStatusAsync(AMRId);
        }
        
        public RobotServices.GetNowAMRStatusResult GetNowAMRStatus(string AMRId) {
            return base.Channel.GetNowAMRStatus(AMRId);
        }
        
        public System.Threading.Tasks.Task<RobotServices.GetNowAMRStatusResult> GetNowAMRStatusAsync(string AMRId) {
            return base.Channel.GetNowAMRStatusAsync(AMRId);
        }
        
        public RobotServices.GetNowAMRErrorsResult GetNowAMRErrors(string AMRId) {
            return base.Channel.GetNowAMRErrors(AMRId);
        }
        
        public System.Threading.Tasks.Task<RobotServices.GetNowAMRErrorsResult> GetNowAMRErrorsAsync(string AMRId) {
            return base.Channel.GetNowAMRErrorsAsync(AMRId);
        }
    }
}
